config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'articles#index'
  get 'analytics', to: 'searches#index'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 2, maximum: 100,
                                              too_long: '100 characters is the maximum allowed' }
  validates :body, presence: true, length: { minimum: 2, maximum: 3000,
                                             too_long: '3000 characters is the maximum allowed' }
  validates :user_id, presence: true

  belongs_to :user
end

app/models/search.rb
class Search < ApplicationRecord
  validates :query, presence: true
  validates :query, length: { minimum: 3 }
  validates :searcher_id, presence: true

  scope :order_by_most_searched, -> { group(:query).pluck('query, count(query) as COUNT').sort_by { |a| a[1] }.reverse }

  def searched?(search)
    require 'fuzzystringmatch'
    jarow = FuzzyStringMatch::JaroWinkler.create(:native)
    similarity_percentage = jarow.getDistance(search, query)
    similarity_percentage > 0.8
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy

  validates :email, presence: true,
                    format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'must be a valid email address' }, uniqueness: true

  validates :password, length: { minimum: 6 }, presence: true
  validates :password_confirmation, length: { minimum: 6 }, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_searcher_id, only: [:index]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @articles = if params[:query].present?
                  Article.where('title LIKE ?', "%#{params[:query]}%")
                else
                  Article.all.first(12)
                end
    filter_search(params[:query], session.id) if @articles
    if turbo_frame_request?
      render partial: 'articles', locals: { articles: @articles }
    else
      render :index
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = current_user.articles.new
  end

  def create
    @article = current_user.articles.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def filter_search(query, session)
    return if query.nil? || query.length < 3

    current_search = Search.where(searcher_id: session.to_s).last
    if current_search.nil? || !current_search.searched?(query)
      Search.create(query: query, searcher_id: session.to_s)
    elsif current_search.query.length < query.length
      current_search.update(query: query)
    end
  end

  def article_params
    params.require(:article).permit(:title, :body)
  end

  def set_searcher_id
    session[:user_id] = SecureRandom.urlsafe_base64(16) if session[:user_id].nil?
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @searches = Search.order_by_most_searched.first(15)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p class="text-lg leading-loose">
    <%= link_to article.title, article_path(article), class: "text-orange-600 underline hover:text-orange-700" %>
  </p>
</div>

app/views/articles/_articles.html.erb
<%= turbo_frame_tag "articles" do %>
  <%= render articles %>
<% end %>

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/index.html.erb
<h1 class="font-bold text-3xl mb-3">Articles</h1>
<div class="input-group m-2">
  <%= form_with(url: articles_path, method: :get, data: {controller: "search-form", turbo_frame: "articles", turbo_action: "advance"}) do |form| %>
    <%= form.label :query, "Search by article name:", class: "form-label" %>
    <%= form.text_field :query, class: "form-control", data: {action: "input->search-form#search"} %>
    <div class="d-grid gap-2">
      <%= form.submit 'Search', class: "btn btn-primary m-1" %>
    </div>
  <% end %>
</div>
<div class="m-3">
  <%= render "articles", articles: @articles %>
</div>
<%= link_to "New Article", new_article_path, class: "btn btn-primary" %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="card">
  <div class="card-header">
    Featured
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @article.title %></h5>
    <p class="card-text"></p>
    <%= @article.body %></p>
  <%= link_to "Back to articles", articles_path, class: "btn btn-primary" %>
</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to 'HOME', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Search Analytics', analytics_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item"> <%= link_to "Edit Account", edit_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"> <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-small btn-primary mx-2" %></li>
        <% else %>
          <li class="nav-item"> <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %></li>
          <li class="nav-item"> <%= link_to "Sign In", new_user_session_path, class: "nav-link"  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealtimeSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
        <%= flash[:alert] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/searches/index.html.erb
<div class="col-xs-12 text-center m-3">
  <h1>All Searches and analytics</h1>
</div>
<table class="table table-Secondary table-hover table-striped ">
  <thead class="table-dark">
    <tr>
      <th scope="col">Search term</th>
      <th scope="col">Time searched by different Users</th>
    </tr>
  </thead>
  <tbody>
    <% if @searches.empty? %>
      <tr>
        <td colspan="4" class="text-center">
          <h3>Nothing have been searched yet!.</h3>
        </td>
      </tr>
    <% end %>
    <%@searches.each do |search| %>
      <tr>
        <th scope="row"><%= search[0]%></th>
        <td>
          <%= search[1] %>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>